version: "3.8"

services:
  krm3_fe:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VERSION}
    ports:
      - "3000:3000"
    volumes:
      - ../:/app  
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - KRM3_FE_API_BASE_URL=http://localhost:8000/api/v1/
